"""
The server -> Android response contract.

The Android accessibility agent reads the reply to a machine turn as
JSON: `{"action": "...", ...}`. That reply is generated by a model, and
it reaches the phone inside a *second* JSON document - the `reply` field
of `ChatResponse`. So there are two layers of escaping between what the
model wrote and what `AgentActionParser` parses, and a bug in the outer
one corrupts the inner one silently: the payload still parses as HTTP
JSON, and the damage only shows up as "the agent stopped working".

This file pins the outer layer. It asserts on `response.content` - the
actual bytes on the wire - rather than on `response.json()`, because
`.json()` is the very decoder whose input is in question, and a test
that round-trips through it would pass on a payload no other client
could read.

What is deliberately NOT tested here: whether a model emits well-formed
JSON. It often does not, which is why `AgentActionParser` tolerates
fences, prose and unknown fields (20 tests in
`android/app/src/test/.../AgentActionParserTest.kt`). The contract this
file defends is narrower and absolute - whatever the model wrote, the
transport delivers unchanged.

Written after a report of "Failed to parse action from server" on a
normal chat message. The cause turned out to be an installed APK older
than the server it was talking to; the transport was correct. These
tests are what makes that conclusion checkable rather than asserted, and
what would catch a real break of the same contract later.
"""

import json

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from memory.manager import MemoryManager
from memory.models import Base
from server import config as server_config
from server.main import app
from server.runtime import init_runtime, shutdown_runtime


TEST_CONFIG = {
    "app": {"name": "Aura", "version": "0.2.0"},
    "llm": {"provider": "mock"},
    "memory": {"history_limit": 20, "profile": True, "recall": False},
    "personality": {},
    "voice": {"tts": {"enabled": False}, "stt": {"enabled": False}},
    "vision": {"enabled": False},
    "avatar": {"enabled": False},
    "tools": {"enabled": False},
    "plugins": {"enabled": False},
}


# One step of the device agent. `accessibility_tree` and `device` are the
# keys `brain.agent_mode.is_agent_tick` reads; the reply to a turn
# carrying them is parsed, not read, and must arrive verbatim.
AGENT_CONTEXT = {
    "device": {"width": 1080, "height": 2400},
    "accessibility_tree": {"nodes": []},
    "user_request": "hello Auraaa",
}


@pytest.fixture(scope="module")
def isolated_memory():
    """See `tests/test_server.py` - same reasoning, same arguments."""

    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(engine)

    session = sessionmaker(bind=engine, expire_on_commit=False)()

    yield MemoryManager(session=session)

    session.close()


@pytest.fixture(scope="module")
def client(isolated_memory):

    previous_token = server_config.settings.auth_token
    server_config.settings.auth_token = ""

    import os

    previous_insecure = os.environ.get(server_config.INSECURE_ENV_VAR)
    os.environ[server_config.INSECURE_ENV_VAR] = "1"

    init_runtime(dict(TEST_CONFIG), memory=isolated_memory)

    try:
        with TestClient(app) as test_client:
            yield test_client
    finally:
        shutdown_runtime()
        server_config.settings.auth_token = previous_token
        if previous_insecure is None:
            os.environ.pop(server_config.INSECURE_ENV_VAR, None)
        else:
            os.environ[server_config.INSECURE_ENV_VAR] = previous_insecure


@pytest.fixture
def says(monkeypatch):
    """
    Make the provider return exactly one string.

    Patching the conversation's `llm` rather than the provider class, so
    the reply travels the real path from `ConversationManager` through
    the route's serializer - which is the half under test.
    """

    from server.runtime import get_runtime

    def fix(reply: str):
        conversation = get_runtime().engine.conversation

        class Fixed:
            provider_name = "mock"

            def generate(self, prompt: str) -> str:
                return reply

            def stream(self, prompt: str):
                yield reply

        monkeypatch.setattr(conversation, "llm", Fixed())

    return fix


def reply_of(response) -> str:
    """
    The `reply` field, decoded from the raw bytes.

    Goes through `json.loads(response.content)` rather than
    `response.json()` to make the decoding step explicit: what is being
    checked is that the bytes on the wire decode to the string the model
    produced, byte for byte.
    """

    assert response.status_code == 200, response.text

    return json.loads(response.content)["reply"]


def tick(client, reply_text, says):
    """One agent tick whose model reply is `reply_text`."""

    says(reply_text)

    return client.post(
        "/api/chat",
        json={
            "session_id": "agent-protocol",
            "message": "tick",
            "context": AGENT_CONTEXT,
        },
    )


# ======================================================================
# The payload survives the transport
# ======================================================================

# Every one of these is a real thing a model puts in a `complete`
# message, and each breaks a different part of a hand-rolled serializer.
# All are *well formed* inner JSON - a newline inside the message is the
# two-character escape `\n`, which is the only spelling valid JSON has.
# The malformed variants live in their own group at the bottom.
#
# `pretty_printed` is the payload from the original report.
ACTIONS = [
    pytest.param('{"action": "home"}', "home", id="minimal"),
    pytest.param(
        '{"action": "complete", "message": "Done."}', "complete", id="complete"
    ),
    pytest.param(
        '{"action": "complete", "message": "Line one\\nLine two"}',
        "complete",
        id="escaped_newline_in_message",
    ),
    pytest.param(
        '{"action": "complete", "message": "I opened \\"Settings\\" for you"}',
        "complete",
        id="escaped_quotes_in_message",
    ),
    pytest.param(
        '{"action": "input_text", "text": "C:\\\\Users\\\\Ember"}',
        "input_text",
        id="backslashes",
    ),
    pytest.param(
        '{"action": "complete", "message": "Xong r\u1ed3i nh\u00e9, b\u1ea1n \u01a1i!"}',
        "complete",
        id="non_ascii",
    ),
    pytest.param(
        '{"action": "complete", "message": "nice {} work"}',
        "complete",
        id="braces_inside_a_string",
    ),
    pytest.param(
        '{\n  "action": "complete",\n  "message": "Hey. Good to see you, '
        'bro. What are we building today?"\n}',
        "complete",
        id="pretty_printed_the_reported_payload",
    ),
    pytest.param(
        '```json\n{"action": "complete", "message": "Fenced"}\n```',
        "complete",
        id="fenced_by_the_model",
    ),
]


@pytest.mark.parametrize("model_reply, expected_action", ACTIONS)
def test_the_action_reaches_the_client_byte_for_byte(
    client, says, model_reply, expected_action
):
    """
    The contract, stated once.

    Not "the reply parses" and not "the reply contains the action" -
    equality. Anything that rewrites the reply on the way out is a bug
    here even if the result happens to still be valid JSON, because the
    phone parses this string and a rewrite is a silent change of
    meaning.
    """

    assert reply_of(tick(client, model_reply, says)) == model_reply


@pytest.mark.parametrize("model_reply, expected_action", ACTIONS)
def test_the_delivered_action_is_itself_parseable(
    client, says, model_reply, expected_action
):
    """
    The half that matters to the phone.

    `AgentActionParser` strips fences and brace-matches before decoding,
    so this mirrors it: take what arrived, and check an action comes out
    with the name the model chose. A payload that survives transport but
    cannot be parsed would satisfy the test above and still break the
    agent.
    """

    delivered = reply_of(tick(client, model_reply, says))

    text = delivered.strip()

    if text.startswith("```"):
        text = text.split("\n", 1)[1].rsplit("```", 1)[0]

    action = json.loads(text[text.index("{"):text.rindex("}") + 1])

    assert action["action"] == expected_action


def test_an_escaped_newline_stays_a_two_character_escape(client, says):
    """
    The specific corruption a hand-rolled serializer produces.

    A newline inside a JSON string is spelled `\\n` - backslash, n. The
    outer document escapes that backslash again, so the wire carries
    `\\\\n` and the phone's decode of the *outer* document hands the
    parser back `\\n`, which its decode of the *inner* one turns into a
    real line break. Two layers, and a serializer that unescapes one
    layer too many delivers a literal 0x0A inside a quoted string, which
    is invalid JSON and would fail on the phone rather than here.
    """

    response = tick(
        client,
        '{"action": "complete", "message": "Line one\\nLine two"}',
        says,
    )

    assert b"\\\\n" in response.content

    delivered = reply_of(response)

    assert "\\n" in delivered
    assert "\n" not in delivered

    assert json.loads(delivered)["message"] == "Line one\nLine two"


def test_a_backslash_survives_as_one_backslash(client, says):
    """
    A Windows path is the case that shows a double-escape immediately:
    one round of over-escaping turns `C:\\Users` into `C:\\\\Users`, and
    the phone would type the wrong thing.
    """

    delivered = reply_of(
        tick(client, '{"action": "input_text", "text": "C:\\\\Users"}', says)
    )

    assert json.loads(delivered)["text"] == "C:\\Users"


def test_the_payload_is_not_truncated(client, says):
    """
    Check 10 from the report: a reply cut off before its closing brace.

    A long `complete` message is where a length cap would first bite, and
    a truncated object is exactly what `extractJsonObject` refuses - it
    scans for a balanced brace and returns null when it runs out of text.
    """

    message = "This is a sentence that repeats. " * 60

    model_reply = json.dumps({"action": "complete", "message": message})

    delivered = reply_of(tick(client, model_reply, says))

    assert delivered == model_reply
    assert delivered.endswith("}")
    assert json.loads(delivered)["message"] == message


def test_the_action_is_delivered_exactly_once(client, says):
    """
    Check 5: an action emitted twice.

    Two concatenated objects would leave `extractJsonObject` reading the
    first and silently discarding the second - or, worse, executing a
    stale action. One `reply`, one object.
    """

    delivered = reply_of(
        tick(client, '{"action": "complete", "message": "Once"}', says)
    )

    assert delivered.count('"action"') == 1

    payload = json.loads(client.post(
        "/api/chat",
        json={
            "session_id": "agent-protocol",
            "message": "tick",
            "context": AGENT_CONTEXT,
        },
    ).content)

    assert sorted(payload) == [
        "message_id", "metadata", "reply", "session_id"
    ]


def test_no_prose_is_mixed_into_the_action(client, says):
    """
    Check 7: the server mixing plain text and a JSON action.

    A machine turn skips styling, the identity anchor and the transcript
    (`brain/conversation.py`), so nothing may prepend a greeting or
    append a sign-off. If one did, the reply would still parse - the
    parser tolerates surrounding prose - but the *conversational* path
    would have leaked into a machine one, and that is how a persona ends
    up narrating device actions.
    """

    model_reply = '{"action": "click", "node_id": "node_1"}'

    delivered = reply_of(tick(client, model_reply, says))

    assert delivered == model_reply
    assert delivered.strip().startswith("{")
    assert delivered.strip().endswith("}")


# ======================================================================
# The other two turn types, for contrast
# ======================================================================

def test_a_normal_chat_turn_is_prose_not_an_action(client, says):
    """
    The turn the report was actually about.

    With no machine context the reply is styled and saved and is not
    expected to be JSON at all - so nothing on the phone should be
    parsing it as an action. This is the contrast that makes the routing
    bug visible: an action-shaped reply here would mean a conversational
    message had been sent down the agent path.
    """

    says("Hey. Good to see you, bro. What are we building today?")

    response = client.post(
        "/api/chat",
        json={"session_id": "prose", "message": "hello Auraaa"},
    )

    assert '"action"' not in reply_of(response)


@pytest.mark.parametrize(
    "model_reply, expected",
    [
        ("action", "action"),
        ("conversation", "conversation"),
        ("Action.", "action"),
        ("  ACTION  ", "action"),
        ("I think this is a conversation", "conversation"),
        ("", "conversation"),
        # The case that matters most here: a model that ignores the
        # one-word instruction and answers with an action object. The
        # word "action" is in it, so a naive reader routes an ordinary
        # greeting into the device loop.
        ('{"action": "complete", "message": "Hey!"}', "action"),
    ],
)
def test_an_intent_probe_is_normalised_to_one_word(
    client, says, model_reply, expected
):
    """
    The probe answers a routing question, and the phone compares two
    strings. Normalising on the server (`server/runtime.py`) is what
    keeps that rule in one place.

    The last case is not a bug being blessed - it is the documented
    behaviour of `read_intent`, which reads word sets, and it is worth
    pinning because it is the one input that can route a greeting into
    the agent loop. A model that answers the intent prompt with an
    action object is a prompt problem, not a transport one.
    """

    says(model_reply)

    response = client.post(
        "/api/chat",
        json={
            "session_id": "probe",
            "message": "hello Auraaa",
            "context": {"intent_probe": True},
        },
    )

    assert reply_of(response) == expected


def test_a_probe_reply_is_never_an_action_object(client, says):
    """
    Whatever the model said, what leaves the server is one of two words.
    An action object reaching the phone from a probe would be parsed as
    an action by a client that only asked how to route.
    """

    says('{\n  "action": "complete",\n  "message": "Hi there"\n}')

    response = client.post(
        "/api/chat",
        json={
            "session_id": "probe",
            "message": "hello Auraaa",
            "context": {"intent_probe": True},
        },
    )

    delivered = reply_of(response)

    assert delivered in {"action", "conversation"}
    assert "{" not in delivered


# ======================================================================
# Streaming
# ======================================================================

def test_streamed_chunks_concatenate_to_the_whole_reply(client, says):
    """
    Check 4. The chat screen accumulates `reply += event.text`, so the
    contract is that concatenating the chunks in index order reproduces
    the reply exactly - no chunk dropped, none duplicated, no separator
    introduced between them.
    """

    says("Hey. Good to see you, bro.")

    with client.websocket_connect(
        "/api/chat/stream?session_id=stream-protocol"
    ) as socket:

        socket.send_json({"message": "hello Auraaa"})

        assert socket.receive_json()["type"] == "started"

        chunks = []

        while True:
            frame = socket.receive_json()
            if frame["type"] != "chunk":
                break
            chunks.append(frame)

        assert frame["type"] == "complete", frame

    assert [c["index"] for c in chunks] == list(range(len(chunks)))

    assert "".join(c["chunk"] for c in chunks) == (
        "Hey. Good to see you, bro."
    )


def test_a_streamed_chunk_carries_its_text_unescaped_once(client, says):
    """
    Every frame is its own JSON document, so a newline inside a chunk is
    escaped by the frame and must decode back to one newline - not to a
    literal `\\n` the user would read as two characters on screen.
    """

    says("first line\nsecond line")

    with client.websocket_connect(
        "/api/chat/stream?session_id=stream-escape"
    ) as socket:

        socket.send_json({"message": "hi"})

        assert socket.receive_json()["type"] == "started"

        text = ""

        while True:
            frame = socket.receive_json()
            if frame["type"] != "chunk":
                break
            text += frame["chunk"]

        assert frame["type"] == "complete", frame

    assert text == "first line\nsecond line"
    assert "\\n" not in text


# ======================================================================
# Malformed replies
# ======================================================================

@pytest.mark.parametrize(
    "model_reply",
    [
        pytest.param("Sure! I'll open that for you.", id="prose_only"),
        pytest.param(
            '{"action": "complete", "message": "cut off',
            id="truncated_object",
        ),
        pytest.param("{}", id="empty_object"),
        pytest.param("", id="empty_reply"),
        # A raw 0x0A inside a quoted string. Invalid JSON, and a model
        # does emit it - which is why it belongs here rather than with
        # the well-formed payloads above.
        pytest.param(
            '{"action": "complete", "message": "Line one\nLine two"}',
            id="literal_newline_inside_a_string",
        ),
    ],
)
def test_a_malformed_action_is_still_delivered_intact(
    client, says, model_reply
):
    """
    The server does not validate the model's JSON, and should not start.

    Every one of these is a reply the phone must decide about, and it has
    the context to do it: `AgentActionParser` returns a `Failure` whose
    reason is fed back as `last_action_error`, which is the model's only
    channel for correcting itself. A server that rejected these would
    turn a recoverable tick into a dead request, and a server that
    "repaired" them would send the phone an action nobody chose.

    So the contract is delivery, not judgement - including of an empty
    reply, which arrives as an empty string rather than a 500.
    """

    assert reply_of(tick(client, model_reply, says)) == model_reply
