"""
The server -> Android response contract.

The Android accessibility agent reads the reply to a machine turn as
JSON: `{"action": "...", ...}`. That reply is generated by a model, and
it reaches the phone inside a *second* JSON document - the `reply` field
of `ChatResponse`. So there are two layers of escaping between what the
model wrote and what `AgentActionParser` parses, and a bug in the outer
one corrupts the inner one silently: the payload still parses as HTTP
JSON, and the damage only shows up as "the agent stopped working".

This file pins the outer layer. It asserts on `response.content` - the
actual bytes on the wire - rather than on `response.json()`, because
`.json()` is the very decoder whose input is in question, and a test
that round-trips through it would pass on a payload no other client
could read.

What is deliberately NOT tested here: whether a model emits well-formed
JSON. It often does not, which is why `AgentActionParser` tolerates
fences, prose and unknown fields (20 tests in
`android/app/src/test/.../AgentActionParserTest.kt`). The contract this
file defends is narrower and absolute - whatever the model wrote, the
transport delivers unchanged.

Written after a report of "Failed to parse action from server" on a
normal chat message. The cause turned out to be an installed APK older
than the server it was talking to; the transport was correct. These
tests are what makes that conclusion checkable rather than asserted, and
what would catch a real break of the same contract later.
"""

import json
import re

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from core.paths import PROJECT_ROOT
from memory.manager import MemoryManager
from memory.models import Base
from server import config as server_config
from server.main import app
from server.runtime import init_runtime, shutdown_runtime


TEST_CONFIG = {
    "app": {"name": "Aura", "version": "0.2.0"},
    "llm": {"provider": "mock"},
    "memory": {"history_limit": 20, "profile": True, "recall": False},
    "personality": {},
    "voice": {"tts": {"enabled": False}, "stt": {"enabled": False}},
    "vision": {"enabled": False},
    "avatar": {"enabled": False},
    "tools": {"enabled": False},
    "plugins": {"enabled": False},
}


# One step of the device agent. `accessibility_tree` and `device` are the
# keys `brain.agent_mode.is_agent_tick` reads; the reply to a turn
# carrying them is parsed, not read, and must arrive verbatim.
AGENT_CONTEXT = {
    "device": {"width": 1080, "height": 2400},
    "accessibility_tree": {"nodes": []},
    "user_request": "hello Auraaa",
}


@pytest.fixture(scope="module")
def isolated_memory():
    """See `tests/test_server.py` - same reasoning, same arguments."""

    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(engine)

    session = sessionmaker(bind=engine, expire_on_commit=False)()

    yield MemoryManager(session=session)

    session.close()


@pytest.fixture(scope="module")
def client(isolated_memory):

    previous_token = server_config.settings.auth_token
    server_config.settings.auth_token = ""

    import os

    previous_insecure = os.environ.get(server_config.INSECURE_ENV_VAR)
    os.environ[server_config.INSECURE_ENV_VAR] = "1"

    init_runtime(dict(TEST_CONFIG), memory=isolated_memory)

    try:
        with TestClient(app) as test_client:
            yield test_client
    finally:
        shutdown_runtime()
        server_config.settings.auth_token = previous_token
        if previous_insecure is None:
            os.environ.pop(server_config.INSECURE_ENV_VAR, None)
        else:
            os.environ[server_config.INSECURE_ENV_VAR] = previous_insecure


@pytest.fixture
def says(monkeypatch):
    """
    Make the provider return exactly one string.

    Patching the conversation's `llm` rather than the provider class, so
    the reply travels the real path from `ConversationManager` through
    the route's serializer - which is the half under test.
    """

    from server.runtime import get_runtime

    def fix(reply: str):
        conversation = get_runtime().engine.conversation

        class Fixed:
            provider_name = "mock"

            def generate(self, prompt: str) -> str:
                return reply

            def stream(self, prompt: str):
                yield reply

        monkeypatch.setattr(conversation, "llm", Fixed())

    return fix


def reply_of(response) -> str:
    """
    The `reply` field, decoded from the raw bytes.

    Goes through `json.loads(response.content)` rather than
    `response.json()` to make the decoding step explicit: what is being
    checked is that the bytes on the wire decode to the string the model
    produced, byte for byte.
    """

    assert response.status_code == 200, response.text

    return json.loads(response.content)["reply"]


def tick(client, reply_text, says):
    """One agent tick whose model reply is `reply_text`."""

    says(reply_text)

    return client.post(
        "/api/chat",
        json={
            "session_id": "agent-protocol",
            "message": "tick",
            "context": AGENT_CONTEXT,
        },
    )


# ======================================================================
# The payload survives the transport
# ======================================================================

# Every one of these is a real thing a model puts in a `complete`
# message, and each breaks a different part of a hand-rolled serializer.
# All are *well formed* inner JSON - a newline inside the message is the
# two-character escape `\n`, which is the only spelling valid JSON has.
# The malformed variants live in their own group at the bottom.
#
# `pretty_printed` is the payload from the original report.
ACTIONS = [
    pytest.param('{"action": "home"}', "home", id="minimal"),
    pytest.param(
        '{"action": "complete", "message": "Done."}', "complete", id="complete"
    ),
    pytest.param(
        '{"action": "complete", "message": "Line one\\nLine two"}',
        "complete",
        id="escaped_newline_in_message",
    ),
    pytest.param(
        '{"action": "complete", "message": "I opened \\"Settings\\" for you"}',
        "complete",
        id="escaped_quotes_in_message",
    ),
    pytest.param(
        '{"action": "input_text", "text": "C:\\\\Users\\\\Ember"}',
        "input_text",
        id="backslashes",
    ),
    pytest.param(
        '{"action": "complete", "message": "Xong r\u1ed3i nh\u00e9, b\u1ea1n \u01a1i!"}',
        "complete",
        id="non_ascii",
    ),
    pytest.param(
        '{"action": "complete", "message": "nice {} work"}',
        "complete",
        id="braces_inside_a_string",
    ),
    pytest.param(
        '{\n  "action": "complete",\n  "message": "Hey. Good to see you, '
        'bro. What are we building today?"\n}',
        "complete",
        id="pretty_printed_the_reported_payload",
    ),
    pytest.param(
        '```json\n{"action": "complete", "message": "Fenced"}\n```',
        "complete",
        id="fenced_by_the_model",
    ),
]


@pytest.mark.parametrize("model_reply, expected_action", ACTIONS)
def test_the_action_reaches_the_client_byte_for_byte(
    client, says, model_reply, expected_action
):
    """
    The contract, stated once.

    Not "the reply parses" and not "the reply contains the action" -
    equality. Anything that rewrites the reply on the way out is a bug
    here even if the result happens to still be valid JSON, because the
    phone parses this string and a rewrite is a silent change of
    meaning.
    """

    assert reply_of(tick(client, model_reply, says)) == model_reply


@pytest.mark.parametrize("model_reply, expected_action", ACTIONS)
def test_the_delivered_action_is_itself_parseable(
    client, says, model_reply, expected_action
):
    """
    The half that matters to the phone.

    `AgentActionParser` strips fences and brace-matches before decoding,
    so this mirrors it: take what arrived, and check an action comes out
    with the name the model chose. A payload that survives transport but
    cannot be parsed would satisfy the test above and still break the
    agent.
    """

    delivered = reply_of(tick(client, model_reply, says))

    text = delivered.strip()

    if text.startswith("```"):
        text = text.split("\n", 1)[1].rsplit("```", 1)[0]

    action = json.loads(text[text.index("{"):text.rindex("}") + 1])

    assert action["action"] == expected_action


def test_an_escaped_newline_stays_a_two_character_escape(client, says):
    """
    The specific corruption a hand-rolled serializer produces.

    A newline inside a JSON string is spelled `\\n` - backslash, n. The
    outer document escapes that backslash again, so the wire carries
    `\\\\n` and the phone's decode of the *outer* document hands the
    parser back `\\n`, which its decode of the *inner* one turns into a
    real line break. Two layers, and a serializer that unescapes one
    layer too many delivers a literal 0x0A inside a quoted string, which
    is invalid JSON and would fail on the phone rather than here.
    """

    response = tick(
        client,
        '{"action": "complete", "message": "Line one\\nLine two"}',
        says,
    )

    assert b"\\\\n" in response.content

    delivered = reply_of(response)

    assert "\\n" in delivered
    assert "\n" not in delivered

    assert json.loads(delivered)["message"] == "Line one\nLine two"


def test_a_backslash_survives_as_one_backslash(client, says):
    """
    A Windows path is the case that shows a double-escape immediately:
    one round of over-escaping turns `C:\\Users` into `C:\\\\Users`, and
    the phone would type the wrong thing.
    """

    delivered = reply_of(
        tick(client, '{"action": "input_text", "text": "C:\\\\Users"}', says)
    )

    assert json.loads(delivered)["text"] == "C:\\Users"


def test_the_payload_is_not_truncated(client, says):
    """
    Check 10 from the report: a reply cut off before its closing brace.

    A long `complete` message is where a length cap would first bite, and
    a truncated object is exactly what `extractJsonObject` refuses - it
    scans for a balanced brace and returns null when it runs out of text.
    """

    message = "This is a sentence that repeats. " * 60

    model_reply = json.dumps({"action": "complete", "message": message})

    delivered = reply_of(tick(client, model_reply, says))

    assert delivered == model_reply
    assert delivered.endswith("}")
    assert json.loads(delivered)["message"] == message


def test_the_action_is_delivered_exactly_once(client, says):
    """
    Check 5: an action emitted twice.

    Two concatenated objects would leave `extractJsonObject` reading the
    first and silently discarding the second - or, worse, executing a
    stale action. One `reply`, one object.
    """

    delivered = reply_of(
        tick(client, '{"action": "complete", "message": "Once"}', says)
    )

    assert delivered.count('"action"') == 1

    payload = json.loads(client.post(
        "/api/chat",
        json={
            "session_id": "agent-protocol",
            "message": "tick",
            "context": AGENT_CONTEXT,
        },
    ).content)

    assert sorted(payload) == [
        "message_id", "metadata", "reply", "session_id"
    ]


def test_no_prose_is_mixed_into_the_action(client, says):
    """
    Check 7: the server mixing plain text and a JSON action.

    A machine turn skips styling, the identity anchor and the transcript
    (`brain/conversation.py`), so nothing may prepend a greeting or
    append a sign-off. If one did, the reply would still parse - the
    parser tolerates surrounding prose - but the *conversational* path
    would have leaked into a machine one, and that is how a persona ends
    up narrating device actions.
    """

    model_reply = '{"action": "click", "node_id": "node_1"}'

    delivered = reply_of(tick(client, model_reply, says))

    assert delivered == model_reply
    assert delivered.strip().startswith("{")
    assert delivered.strip().endswith("}")


# ======================================================================
# The other two turn types, for contrast
# ======================================================================

def test_a_normal_chat_turn_is_prose_not_an_action(client, says):
    """
    The turn the report was actually about.

    With no machine context the reply is styled and saved and is not
    expected to be JSON at all - so nothing on the phone should be
    parsing it as an action. This is the contrast that makes the routing
    bug visible: an action-shaped reply here would mean a conversational
    message had been sent down the agent path.
    """

    says("Hey. Good to see you, bro. What are we building today?")

    response = client.post(
        "/api/chat",
        json={"session_id": "prose", "message": "hello Auraaa"},
    )

    assert '"action"' not in reply_of(response)


@pytest.mark.parametrize(
    "model_reply, expected",
    [
        ("action", "action"),
        ("conversation", "conversation"),
        ("Action.", "action"),
        ("  ACTION  ", "action"),
        ("I think this is a conversation", "conversation"),
        ("", "conversation"),
        # The case that matters most here: a model that ignores the
        # one-word instruction and answers with an action object. The
        # word "action" is in it, so a naive reader routes an ordinary
        # greeting into the device loop.
        ('{"action": "complete", "message": "Hey!"}', "action"),
    ],
)
def test_an_intent_probe_is_normalised_to_one_word(
    client, says, model_reply, expected
):
    """
    The probe answers a routing question, and the phone compares two
    strings. Normalising on the server (`server/runtime.py`) is what
    keeps that rule in one place.

    The last case is not a bug being blessed - it is the documented
    behaviour of `read_intent`, which reads word sets, and it is worth
    pinning because it is the one input that can route a greeting into
    the agent loop. A model that answers the intent prompt with an
    action object is a prompt problem, not a transport one.
    """

    says(model_reply)

    response = client.post(
        "/api/chat",
        json={
            "session_id": "probe",
            "message": "hello Auraaa",
            "context": {"intent_probe": True},
        },
    )

    assert reply_of(response) == expected


def test_a_probe_reply_is_never_an_action_object(client, says):
    """
    Whatever the model said, what leaves the server is one of two words.
    An action object reaching the phone from a probe would be parsed as
    an action by a client that only asked how to route.
    """

    says('{\n  "action": "complete",\n  "message": "Hi there"\n}')

    response = client.post(
        "/api/chat",
        json={
            "session_id": "probe",
            "message": "hello Auraaa",
            "context": {"intent_probe": True},
        },
    )

    delivered = reply_of(response)

    assert delivered in {"action", "conversation"}
    assert "{" not in delivered


# ======================================================================
# Streaming
# ======================================================================

def test_streamed_chunks_concatenate_to_the_whole_reply(client, says):
    """
    Check 4. The chat screen accumulates `reply += event.text`, so the
    contract is that concatenating the chunks in index order reproduces
    the reply exactly - no chunk dropped, none duplicated, no separator
    introduced between them.
    """

    says("Hey. Good to see you, bro.")

    with client.websocket_connect(
        "/api/chat/stream?session_id=stream-protocol"
    ) as socket:

        socket.send_json({"message": "hello Auraaa"})

        assert socket.receive_json()["type"] == "started"

        chunks = []

        while True:
            frame = socket.receive_json()
            if frame["type"] != "chunk":
                break
            chunks.append(frame)

        assert frame["type"] == "complete", frame

    assert [c["index"] for c in chunks] == list(range(len(chunks)))

    assert "".join(c["chunk"] for c in chunks) == (
        "Hey. Good to see you, bro."
    )


def test_a_streamed_chunk_carries_its_text_unescaped_once(client, says):
    """
    Every frame is its own JSON document, so a newline inside a chunk is
    escaped by the frame and must decode back to one newline - not to a
    literal `\\n` the user would read as two characters on screen.
    """

    says("first line\nsecond line")

    with client.websocket_connect(
        "/api/chat/stream?session_id=stream-escape"
    ) as socket:

        socket.send_json({"message": "hi"})

        assert socket.receive_json()["type"] == "started"

        text = ""

        while True:
            frame = socket.receive_json()
            if frame["type"] != "chunk":
                break
            text += frame["chunk"]

        assert frame["type"] == "complete", frame

    assert text == "first line\nsecond line"
    assert "\\n" not in text


# ======================================================================
# Malformed replies
# ======================================================================

@pytest.mark.parametrize(
    "model_reply",
    [
        pytest.param("Sure! I'll open that for you.", id="prose_only"),
        pytest.param(
            '{"action": "complete", "message": "cut off',
            id="truncated_object",
        ),
        pytest.param("{}", id="empty_object"),
        pytest.param("", id="empty_reply"),
        # A raw 0x0A inside a quoted string. Invalid JSON, and a model
        # does emit it - which is why it belongs here rather than with
        # the well-formed payloads above.
        pytest.param(
            '{"action": "complete", "message": "Line one\nLine two"}',
            id="literal_newline_inside_a_string",
        ),
    ],
)
def test_a_malformed_action_is_still_delivered_intact(
    client, says, model_reply
):
    """
    The server does not validate the model's JSON, and should not start.

    Every one of these is a reply the phone must decide about, and it has
    the context to do it: `AgentActionParser` returns a `Failure` whose
    reason is fed back as `last_action_error`, which is the model's only
    channel for correcting itself. A server that rejected these would
    turn a recoverable tick into a dead request, and a server that
    "repaired" them would send the phone an action nobody chose.

    So the contract is delivery, not judgement - including of an empty
    reply, which arrives as an empty string rather than a 500.
    """

    assert reply_of(tick(client, model_reply, says)) == model_reply


# ======================================================================
# The action vocabulary, across the language boundary
# ======================================================================

KOTLIN_PARSER = (
    PROJECT_ROOT
    / "android/app/src/main/java/com/aura/companion/accessibility"
    / "AgentActionParser.kt"
)


def offered_actions() -> set[str]:
    """
    Every action the AGENT RULES section tells the model it may use.

    Read out of the rendered prompt rather than out of a constant, because
    the prompt is what the model actually sees. A list that agreed with a
    constant while disagreeing with the prompt would prove nothing.
    """

    from brain.message import Message
    from brain.prompt_builder import PromptBuilder

    prompt = PromptBuilder().build(
        history=[],
        user_message=Message(role="user", content="agent_tick"),
        context={"device": {}, "accessibility_tree": {}},
    )

    line = next(
        (
            text for text in prompt.splitlines()
            if text.strip().startswith('"action":') and "|" in text
        ),
        None,
    )

    assert line is not None, (
        "the AGENT RULES prompt no longer contains an '\"action\": a | b' "
        "enum line. If the format changed, update this reader - the "
        "agreement it checks had already broken once."
    )

    return set(re.findall(r'"(\w+)"', line)) - {"action"}


def accepted_actions() -> set[str]:
    """
    Every action `AgentActionParser.KNOWN_ACTIONS` will let through.

    Parsed out of the Kotlin source. Crude, and the only option available:
    the allow list is a Kotlin `Set<String>` and the prompt is a Python
    f-string, so no single test runtime can import both. The alternative
    is what the repository had until now - a comment on `KNOWN_ACTIONS`
    saying it is "kept in step with the supported set listed in the AGENT
    RULES prompt section", which is a promise nothing checked.
    """

    source = KOTLIN_PARSER.read_text(encoding="utf-8")

    marker = "val KNOWN_ACTIONS"
    assert marker in source, (
        f"{KOTLIN_PARSER.name} no longer declares {marker}. If the allow "
        f"list was renamed or moved, point this reader at it - do not "
        f"delete the check, because the drift it caught was real."
    )

    body = source.split(marker, 1)[1].split(")", 1)[0]
    names = set(re.findall(r'"(\w+)"', body))

    assert names, (
        f"parsed no action names out of {KOTLIN_PARSER.name}'s {marker}. "
        f"Read as: {body!r}"
    )

    return names


def test_the_parser_accepts_every_action_the_prompt_offers():
    """
    The drift this catches was live, and it cost the agent a step.

    The prompt offered `submit`, `AuraActionExecutor` implemented it, and
    `AuraAccessibilityService`'s completion heuristics tested for it - but
    `KNOWN_ACTIONS` did not contain it. So a model doing exactly as it was
    told was answered with `"submit" is not a supported action`, and that
    rejection spends one of three parse failures before the task is
    abandoned. Section 23's search flow ends in submit, so the mandated
    scenario could not complete.

    Asserted in this direction because it is the harmful one: an action
    offered but not accepted punishes obedience.
    """

    missing = offered_actions() - accepted_actions()

    assert not missing, (
        f"the AGENT RULES prompt offers {sorted(missing)}, which "
        f"AgentActionParser.KNOWN_ACTIONS rejects"
    )


def test_the_parser_offers_nothing_the_prompt_does_not():
    """
    The other direction, which is untidy rather than harmful.

    An action the parser accepts but the prompt never mentions is
    unreachable: no model will emit a name it was not given. `complete` is
    the one deliberate exception - it is the terminal action, described in
    its own block above the supported set rather than inside it.
    """

    extra = accepted_actions() - offered_actions() - {"complete"}

    assert not extra, (
        f"AgentActionParser.KNOWN_ACTIONS accepts {sorted(extra)}, which "
        f"the AGENT RULES prompt never offers"
    )


# ======================================================================
# The search-verb vocabulary, across the language boundary
# ======================================================================

KOTLIN_EXECUTOR = (
    PROJECT_ROOT
    / "android/app/src/main/java/com/aura/companion/accessibility"
    / "AuraActionExecutor.kt"
)


def device_search_verbs() -> list[str]:
    """
    The device's search vocabulary, in order.

    Read out of the Kotlin source for the same reason the action names
    are: a Python-side copy of the list would agree with itself forever
    while the device drifted, which is precisely how `submit` came to be
    offered by the prompt and rejected by the parser.

    It used to be a local `val prefixes` inside `sanitizeSearchQuery`,
    which was its only reader. `shouldAutoComplete` is now a second one -
    a request containing a search verb is not finished by a launch - so
    the list is a companion constant and this guard reads that.
    """

    source = KOTLIN_EXECUTOR.read_text(encoding="utf-8")
    marker = "val SEARCH_VERBS = listOf("

    assert marker in source, (
        f"{KOTLIN_EXECUTOR.name} no longer declares `{marker}`. If the "
        "search vocabulary moved or was renamed, point this guard at its "
        "new home rather than deleting it - the lists still have to agree."
    )

    body = source.split(marker, 1)[1].split(")", 1)[0]
    verbs = [text.strip() for text in re.findall(r'"([^"]*)"', body)]

    assert verbs, f"found `{marker}` in {KOTLIN_EXECUTOR.name} but no strings in it"

    return verbs


def test_both_sides_strip_the_same_search_verbs():
    # The server now decides the query up front (`brain.planner.plan_for`)
    # and the device still cleans up whatever the model produced. Two
    # implementations of one rule in two languages is exactly the shape
    # that broke last time, so the vocabulary is pinned rather than
    # commented.
    from brain.planner import SEARCH_VERBS

    assert list(SEARCH_VERBS) == device_search_verbs()


def test_the_longest_verb_is_tried_first_on_both_sides():
    # Order is behaviour, not style. If "search" were tried before
    # "search for", the query for "search for Minecraft" would come out as
    # "for Minecraft" - and the side that reordered would be the only one
    # doing it, so the equality above would fail without saying why.
    from brain.planner import SEARCH_VERBS

    for verbs in (list(SEARCH_VERBS), device_search_verbs()):
        for earlier in range(len(verbs)):
            for later in range(earlier + 1, len(verbs)):
                assert not verbs[later].startswith(verbs[earlier] + " "), (
                    f'"{verbs[later]}" is listed after "{verbs[earlier]}", '
                    f'which is its own prefix - so "{verbs[later]} x" would '
                    f'be read as "{verbs[earlier]}" followed by a query '
                    f'beginning "{verbs[later][len(verbs[earlier]) + 1:]}"'
                )


# ======================================================================
# Who owns "done", across the language boundary
# ======================================================================


def device_multi_step_keywords() -> list[str]:
    """
    The separators `shouldAutoComplete` reads as "more than one thing".

    Read out of the Kotlin source, like the search verbs and the retry
    ceiling, because the whole point is to catch the two sides drifting.
    """

    source = KOTLIN_SERVICE.read_text(encoding="utf-8")
    marker = "val multiStepKeywords = listOf("

    assert marker in source, (
        f"{KOTLIN_SERVICE.name} no longer declares `{marker}`. If the "
        "early-exit test moved or was renamed, point this guard at its "
        "new home rather than deleting it."
    )

    body = source.split(marker, 1)[1].split(")", 1)[0]
    keywords = re.findall(r'"([^"]*)"', body)

    assert keywords, f"found `{marker}` in {KOTLIN_SERVICE.name} but no strings"

    return keywords


def device_early_exit_body() -> str:
    """
    The body of `shouldAutoComplete`, as text.

    Needed because the test below asserts over vocabularies, and a
    vocabulary the function declares and never reads would satisfy it
    vacuously - which is exactly the state the device was in before phase
    17: the search verbs existed on the device, in the query sanitiser,
    and the early exit did not look at them.
    """

    source = KOTLIN_SERVICE.read_text(encoding="utf-8")
    marker = "fun shouldAutoComplete("

    assert marker in source, (
        f"{KOTLIN_SERVICE.name} no longer declares `{marker}`. If the "
        "early exit was renamed, point this guard at its new name."
    )

    body = source.split(marker, 1)[1]
    end = body.find("\n        }")

    assert end > 0, "could not find the end of `shouldAutoComplete`"

    return body[:end]


def test_the_early_exit_reads_both_kinds_of_signal():
    """
    Both lists are consulted, not merely declared.

    The test below checks that a multi-step request contains something the
    device recognises. That is only meaningful if the device reads it, so
    this pins the two references. Structural rather than behavioural on
    purpose: the behaviour is asserted in Kotlin, by
    `AccessibilityAgentTest.testTwoVerbsWithNoConjunctionIsNotSingleStep`,
    where the function can actually be called.
    """

    body = device_early_exit_body()

    assert "multiStepKeywords" in body, (
        "`shouldAutoComplete` no longer reads its conjunction list, so a "
        "two-clause request would be called single-step"
    )
    assert "SEARCH_VERBS" in body, (
        "`shouldAutoComplete` no longer reads the shared search "
        "vocabulary, so \"mở YouTube tìm nhạc\" - two jobs, no conjunction "
        "- would be reported finished after the launch"
    )


def multi_step_phrasings() -> list[str]:
    """
    Requests that ask for two things, generated from the planner's own
    vocabulary rather than chosen by hand.

    Hand-picked strings prove whatever the author already believed. These
    are every combination of a launch verb, an app, a separator and a
    search verb - including the empty separator, which is the case that
    was broken: "mở YouTube tìm nhạc" names two jobs and no conjunction.
    """

    from brain.planner import LAUNCH_VERBS, SEARCH_VERBS

    separators = ("", " ") + tuple(f"{c}" for c in (" and ", " rồi ", ", "))
    requests = []

    for launch in LAUNCH_VERBS:
        for app in ("YouTube", "Chrome"):
            for separator in separators:
                for search in SEARCH_VERBS:
                    requests.append(
                        f"{launch} {app}{separator or ' '}{search} Minecraft"
                    )

    return requests


def test_no_multi_step_request_satisfies_the_device_early_exit():
    """
    The device may stop early only where the server sees one step.

    Two authorities decide when an agent task ends, and only one of them
    owns the question. The server owns "is the goal met": `plan_for`
    decomposes the request, `task_graph.build` reads it against what
    happened, and the model ends the task by saying `complete`. The
    device's `shouldAutoComplete` owns something narrower - whether one
    navigation step so plainly was the whole request that another round
    trip to hear `complete` is waste.

    Being wrong in that judgement is not a wasted round trip, it is a
    truncated task: the loop reports "App launched successfully!" for a
    request that asked for a search. So the device's answer has to be
    conservative wherever the planner sees work remaining.

    It was not. `shouldAutoComplete` tested only for a conjunction, while
    `plan_for` decomposes on a conjunction *or* on a launch verb and a
    search verb appearing together - and `planner.CONJUNCTIONS` claimed
    in a comment to be "deliberately the same set" as the device's list.
    Every phrasing here without a conjunction was decomposed into five
    steps by the planner and reported as finished by the device after
    step one.

    Asserted over the vocabularies rather than by re-implementing the
    Kotlin predicate: what has to hold is that some signal the device
    actually looks at is present in the text. The Kotlin side of the
    behaviour is covered by `AccessibilityAgentTest`.
    """

    from brain.planner import plan_for

    signals = [
        keyword.strip()
        for keyword in device_multi_step_keywords() + device_search_verbs()
    ]

    for request in multi_step_phrasings():
        steps = len(plan_for(request).steps)

        if steps < 2:
            continue

        assert any(signal in request.lower() for signal in signals), (
            f"the planner decomposes {request!r} into {steps} steps, and "
            "nothing in it is a signal `shouldAutoComplete` reads - so the "
            "device would report the task finished after the launch"
        )


def device_search_completion_body() -> str:
    """The body of `isSearchTaskComplete`, as text."""

    source = KOTLIN_SERVICE.read_text(encoding="utf-8")
    marker = "fun isSearchTaskComplete("

    assert marker in source, (
        f"{KOTLIN_SERVICE.name} no longer declares `{marker}`. If it was "
        "renamed, point this guard at its new name."
    )

    body = source.split(marker, 1)[1]
    end = body.find("\n        }")

    assert end > 0, "could not find the end of `isSearchTaskComplete`"

    return body[:end]


def trailing_clause_phrasings() -> list[str]:
    """
    Search requests with a job named after the search.

    Generated from the planner's own vocabulary and its own conjunctions,
    so the corpus is not a list of the cases the author happened to think
    of. The trailing verbs include ones the device's selection list does
    not carry, which is the half that was invisible.
    """

    from brain.planner import LAUNCH_VERBS, SEARCH_VERBS, CONJUNCTIONS

    requests = []

    for launch in LAUNCH_VERBS:
        for search in SEARCH_VERBS:
            for conjunction in CONJUNCTIONS:
                for trailing in ("tap the result", "click it", "open settings"):
                    requests.append(
                        f"{launch} YouTube and {search} Minecraft"
                        f"{conjunction}{trailing}"
                    )

    return requests


def test_a_job_after_the_search_is_visible_to_the_device():
    """
    The device may not call a search finished while work remains.

    Same ownership boundary as the early exit, at a later point in the
    task. `isSearchTaskComplete` stops the loop the moment a query is
    submitted, and it used to decline only when the request asked for a
    *selection* - so "search Minecraft then open settings" ended at the
    submit and the trailing job never happened. Three of the phrasings
    here end in a verb the selection list does not carry at all, which is
    why the fix is positional rather than another word in a list.

    Asserted over vocabularies for the reason the early-exit test is: the
    property that has to hold is that a separator the device reads sits to
    the right of the search verb. The behaviour is asserted in Kotlin, by
    `AccessibilityAgentTest.testATrailingClauseKeepsTheSearchTaskOpen`.
    """

    from brain.planner import plan_for, SEARCH_VERBS

    conjunctions = [k.strip() for k in device_multi_step_keywords()]
    verbs = [v.strip() for v in device_search_verbs()]

    for request in trailing_clause_phrasings():
        low = request.lower()
        steps = [step.kind.value for step in plan_for(request).steps]

        if "await_results" not in steps or steps[-1] == "await_results":
            continue

        last_verb = max(low.rfind(verb) for verb in verbs)

        assert last_verb >= 0, f"no device search verb in {request!r}"
        assert any(
            low.find(keyword, last_verb) > last_verb
            for keyword in conjunctions
        ), (
            f"the planner reads {request!r} as {steps}, so work remains "
            "after the search, and no separator the device reads sits "
            "after the search verb - the loop would stop at the submit"
        )


def test_the_search_completion_defers_on_a_trailing_clause():
    """
    `isSearchTaskComplete` consults the positional check.

    Without this the test above is vacuous: the conjunctions would be
    present in the text and unread, which is the state the device was in.
    """

    body = device_search_completion_body()

    assert "hasClauseAfterSearch" in body, (
        "`isSearchTaskComplete` no longer asks whether a clause follows "
        "the search, so a request naming a job after the search would be "
        "reported finished at the submit"
    )
    assert "selectionCues" in body, (
        "`isSearchTaskComplete` no longer declines on a selection request, "
        "so \"search Minecraft and play the first video\" would end "
        "before anything was played"
    )


def test_the_device_conjunctions_cover_the_planners():
    """
    Every separator the planner splits on, the device also reads.

    The two lists are allowed to differ, and they do - the device keeps
    " tiếp " and " to ", and bare "," and ";" where the planner wants a
    following space. All of those make the device answer "more than one
    thing" where the planner says one, which is the direction that costs
    a round trip instead of an unfinished task.

    The reverse would be the bug: a separator the planner treats as a
    clause boundary and the device does not means the device stops at the
    first clause. `CONJUNCTIONS` used to claim the two sets were equal;
    this asserts the containment that actually has to hold.
    """

    from brain.planner import CONJUNCTIONS

    device = [keyword.strip() for keyword in device_multi_step_keywords()]

    for conjunction in CONJUNCTIONS:
        assert any(keyword in conjunction for keyword in device), (
            f"the planner splits a request on {conjunction!r} and no "
            "keyword the device reads appears in it, so the device would "
            "call a two-clause request single-step and stop after the first"
        )


# ======================================================================
# The retry bound, across the language boundary
# ======================================================================

KOTLIN_SERVICE = (
    PROJECT_ROOT
    / "android/app/src/main/java/com/aura/companion/accessibility"
    / "AuraAccessibilityService.kt"
)


def device_attempt_ceiling() -> int:
    """
    How many attempts `AuraAccessibilityService` will actually perform.

    Read out of the Kotlin for the same reason the verbs above are. This
    number is not advice - past it the service stops executing the action
    at all - so it is the ceiling on anything the server decides about
    retrying, and a Python-side copy would agree with itself forever while
    the phone drifted.
    """

    source = KOTLIN_SERVICE.read_text(encoding="utf-8")
    marker = "const val MAX_ACTION_ATTEMPTS"

    assert marker in source, (
        f"{KOTLIN_SERVICE.name} no longer declares `{marker}`. If the retry "
        "ceiling moved or was renamed, point this guard at its new home "
        "rather than deleting it - a server bound above what the device "
        "will perform is permission the phone declines to honour."
    )

    match = re.search(re.escape(marker) + r"\s*(?::\s*Int\s*)?=\s*(\d+)", source)

    assert match, f"found `{marker}` in {KOTLIN_SERVICE.name} but no number after it"

    return int(match.group(1))


def test_the_server_never_asks_for_more_attempts_than_the_device_performs():
    # The floor `DEFAULT_RETRY_LIMIT` was chosen against. Above the ceiling
    # the server would keep offering an action the service silently refuses,
    # and the plan would show a step still being tried while nothing on the
    # phone moved. At or below it, the bound is real: the server declining
    # to ask is the whole mechanism.
    from brain.recovery import DEFAULT_RETRY_LIMIT, RETRY_LIMITS

    ceiling = device_attempt_ceiling()

    assert DEFAULT_RETRY_LIMIT <= ceiling, (
        f"DEFAULT_RETRY_LIMIT is {DEFAULT_RETRY_LIMIT} but the device stops "
        f"executing at {ceiling}"
    )

    for kind, limit in RETRY_LIMITS.items():
        assert limit <= ceiling, (
            f"RETRY_LIMITS[{kind!r}] is {limit} but the device stops "
            f"executing at {ceiling}"
        )


def device_failure_verdicts() -> set[str]:
    """
    The verdict words the device puts on a `failed_actions` line.

    Read off the `formatActionFailure` call sites rather than off a Kotlin
    constant, because the call sites are what a tick actually carries. A
    constant listing a verdict nobody emits, or a call site passing one
    nothing declares, would both pass a check against the constant.
    """

    source = KOTLIN_SERVICE.read_text(encoding="utf-8")
    verdicts = set(re.findall(r'formatActionFailure\(\s*action\s*,\s*"([^"]+)"', source))

    assert verdicts, (
        f"{KOTLIN_SERVICE.name} no longer calls `formatActionFailure` with a "
        "literal verdict. If failure reporting moved or was renamed, point "
        "this guard at its new home rather than deleting it - the server's "
        "reader only knows the words the device sends."
    )

    return verdicts


def test_both_sides_agree_on_what_a_failure_verdict_says():
    # The device's vocabulary is the contract; `_FAILED_ACTION` is a reader
    # of it. A verdict the regex does not list is not a parse error - the
    # line is skipped - so the failure would vanish silently, the attempt
    # would never be counted, and the step would look untried forever.
    from brain.agent_mode import _FAILED_ACTION
    from brain.recovery import FAILURE_DETAIL

    readable = set(re.findall(r"[A-Z]{3,}", _FAILED_ACTION.pattern))
    emitted = device_failure_verdicts()

    assert emitted <= readable, (
        f"the device sends {sorted(emitted - readable)}, which "
        "`_FAILED_ACTION` will not match - those lines would be dropped in "
        "silence"
    )

    # And each one has a reason to show the model. `detail_for` falls back,
    # so a gap here is not a crash; it is the plan telling the user "did not
    # complete" when the device knew something more useful.
    assert emitted <= set(FAILURE_DETAIL), (
        f"the device sends {sorted(emitted - set(FAILURE_DETAIL))}, which "
        "`FAILURE_DETAIL` has no wording for"
    )
