"""
Deterministic claim extraction.

Phase 4 must not depend on a second model, and the audit confirmed the
repository does not need heavy linguistic machinery: response prose is
short, generated by one system, and the claim classes the contract names
are recognisable with a small, explicit pattern table.

This module therefore trades generality for determinism. `extract_claims`
splits a reply into sentences and classifies each against a fixed table
of EN/VI patterns. Sentences that match nothing are `GENERAL` and are
left completely alone - ordinary knowledge ("Python is a programming
language") is not tool-grounded and must not be forced through the
evidence machinery. That escape hatch is what keeps the verifier from
making Aura unusably strict.

The second half of that escape hatch is the grounding scope: a claim is
only treated strictly when it names something in the user's world
(`_WORLD_OBJECT`). A side-effect verb alone is not enough - "I checked
the docs" and "I checked your calendar" share a verb and nothing else -
so the object noun is what decides, deterministically.

The patterns deliberately use word boundaries and exact verb forms, never
substring guessing, so a claim like "I understand" can never be read as
an action claim just because it contains the letters "und".
"""

import re
from dataclasses import dataclass, field

from brain.verify.status import ClaimState


class ClaimType(str, object):
    """
    The claim classes the Phase 4 contract names, plus GENERAL for the
    pass-through sentences.

    ACTION          "I sent the email.", "Your calendar event was created."
    FACTUAL         "The file contains 42 records.", "It is 3pm now."
    CAPABILITY      "I can open apps.", "I don't have access to your phone."
    TEMPORAL        a current-state or time-anchored claim
    NUMERICAL       a claim carrying a count ("3 appointments")
    IDENTITY        a claim about the user's state ("your phone has X")
    MEMORY_DERIVED  a claim that echoes a recalled memory line
    GENERAL         nothing actionable; the verifier leaves it alone
    """

    ACTION = "ACTION"
    FACTUAL = "FACTUAL"
    CAPABILITY = "CAPABILITY"
    TEMPORAL = "TEMPORAL"
    NUMERICAL = "NUMERICAL"
    IDENTITY = "IDENTITY"
    MEMORY_DERIVED = "MEMORY_DERIVED"
    GENERAL = "GENERAL"


# ----------------------------------------------------------------------
# Sentence splitting
# ----------------------------------------------------------------------

# Sentence ends at .!? followed by whitespace or end-of-text. Abbreviations
# ("Dr."), initials ("J.") and decimals ("3.13") are filtered in the loop,
# not here - a look-behind on the punctuation cannot distinguish "out."
# from "Dr." because both follow a letter.
_SENTENCE_END = re.compile(r"[.!?]+(?=\s|$)")

_ABBREVIATIONS = frozenset(
    {
        "e.g.", "i.e.", "etc.", "vs.", "mr.", "mrs.", "ms.", "dr.",
        "st.", "approx.", "fig.", "no.", "vol.", "cf.", "al.",
        "inc.", "ltd.", "co.",
    }
)


def _split_sentences(text: str) -> list[str]:
    """Split into sentences, keeping the trailing tail sentence."""

    text = (text or "").strip()

    if not text:
        return []

    sentences: list[str] = []
    rest = text

    while True:

        match = _SENTENCE_END.search(rest)

        if match is None:
            tail = rest.strip()
            if tail:
                sentences.append(tail)
            break

        end = match.end()
        candidate = rest[:end].strip()

        if _is_false_end(rest, match):
            # Not a real sentence boundary: rescan after this punctuation.
            rest = rest[match.start() + 1:]
            continue

        if candidate:
            sentences.append(candidate)

        rest = rest[end:].lstrip()

    return sentences


def _is_false_end(text: str, match: re.Match) -> bool:
    """
    Whether this punctuation match is NOT a sentence boundary.

    Handles exactly the three cases the contract needs, deterministically:

    - an abbreviation ("e.g.", "Dr.") as the last word before the dot;
    - a single-letter initial ("J." in "J. Smith");
    - a decimal point inside a number ("3.13"), which the boundary
      lookahead already mostly prevents but "v3 . x" edge shapes do not.
    """

    if text[match.start():match.end()] != ".":
        return False

    prefix = text[:match.start()]
    words = prefix.rsplit(maxsplit=1)
    last = words[-1] if words else ""

    if len(last) == 1 and last.isalpha():
        return True

    if last.lower() in _ABBREVIATIONS or last.lower() + "." in _ABBREVIATIONS:
        return True

    if (
        last.endswith(".")
        and last[:-1].lower() in _ABBREVIATIONS
    ):
        return True

    return False


# ----------------------------------------------------------------------
# Action claims - first person
# ----------------------------------------------------------------------

# Side-effect verbs, the ones the response contract is strict about.
_EN_ACTION_VERBS = (
    "sent", "created", "deleted", "removed", "opened", "closed",
    "launched", "started", "stopped", "changed", "saved", "modified",
    "updated", "added", "installed", "uninstalled", "verified",
    "confirmed", "cancelled", "canceled", "replied", "forwarded",
    "scheduled", "booked", "called", "wrote", "written", "checked",
    "completed", "restarted", "disabled", "enabled", "sent back",
    # Added after the first pass found "I set a reminder for 5pm" and
    # "I turned off your notifications" classified as GENERAL. Every one
    # of these still needs a world object to become an ACTION claim, which
    # is what keeps "I set out three options" and "I moved on" out.
    "set", "turned", "moved", "renamed", "copied", "downloaded",
    "shared", "muted", "unmuted", "locked", "unlocked", "dismissed",
    "snoozed", "toggled",
)

_VI_ACTION_PHRASES = (
    "đã gửi", "đã tạo", "đã xóa", "đã mở", "đã đóng", "đã thay",
    "đã lưu", "đã sửa", "đã cập nhật", "đã thêm", "đã cài", "đã gỡ",
    "đã xác nhận", "đã hủy", "đã trả lời", "đã chuyển", "đã đặt",
    "đã gọi", "đã viết", "đã bật", "đã tắt", "đã kiểm tra",
    "đã hoàn tất", "đã khởi động lại",
)

_EN_ACTION_VERBS_ALT = "|".join(_EN_ACTION_VERBS)

_VI_ACTION_PHRASES_ALT = "|".join(_VI_ACTION_PHRASES)

# ----------------------------------------------------------------------
# Action claims - passive external outcome
# ----------------------------------------------------------------------

# "The email was sent successfully.", "Your file has been deleted.",
# "The recipient received the message."
_EN_PASSIVE_HEADS = r"\b(the|your|my|a|an|this|that|it|nó)\b"
_EN_PASSIVE_AUX = r"\b(was|were|has been|have been|got|đã được|đã bị)\b"

_ACTION_PASSIVE = re.compile(
    rf"{_EN_PASSIVE_HEADS}\s+[^.!?]{{0,40}}?\s*{_EN_PASSIVE_AUX}\s+"
    rf"(?:successfully\s+)?"
    rf"({_EN_ACTION_VERBS_ALT}|{_VI_ACTION_PHRASES_ALT})\b",
    re.IGNORECASE,
)

# External delivery/receipt language that claims a world change.
_EXTERNAL_OUTCOME = re.compile(
    r"\b(received|delivered|delivered to|seen by|read by|"
    r"completed successfully|finished successfully|done successfully)\b",
    re.IGNORECASE,
)

# ----------------------------------------------------------------------
# Capability claims
# ----------------------------------------------------------------------

_VI_CAPABILITY = r"\b(tôi|có thể|không thể)\b"

_CAPABILITY_PATTERN = re.compile(rf"({_VI_CAPABILITY})", re.IGNORECASE)

_EN_CAPABILITY = re.compile(
    r"\b(i|we)\s+(?:"
    r"(?:am|is|are)?\s*(?:able|unable)?\s*to\s+"
    r"|can|could|cannot|can't|couldn't"
    r"|(?:have|has|had)\s+access\s+to"
    r"|(?:do|does|did)\s*(?:not|n't)?\s*have\s+access\s+to"
    r")",
    re.IGNORECASE,
)

_CAPABILITY_PATTERNS = (_CAPABILITY_PATTERN, _EN_CAPABILITY)

# ----------------------------------------------------------------------
# Factual, numeric, temporal, identity claims
# ----------------------------------------------------------------------

_NUMERIC_PATTERN = re.compile(
    r"\b\d+(?:\.\d+)?\b|"
    r"\b(?:one|two|three|four|five|six|seven|eight|nine|ten|"
    r"một|hai|ba|bốn|năm|sáu|bảy|tám|chín|mười)\b",
    re.IGNORECASE,
)

# "you have", "your X", "your phone has ... installed"
_IDENTITY_PATTERN = re.compile(
    r"\b(you have|you don't have|your|tài khoản của bạn|"
    r"điện thoại của bạn)\b",
    re.IGNORECASE,
)

_TEMPORAL_PATTERN = re.compile(
    r"\b(currently|right now|at the moment|today|tonight|tomorrow|"
    r"this week|this month|yesterday|now|hiện tại|bây giờ|"
    r"ngay bây giờ|hôm nay|tối nay|ngày mai|hôm qua)\b",
    re.IGNORECASE,
)

# ----------------------------------------------------------------------
# The grounding scope
# ----------------------------------------------------------------------

# The closed vocabulary of things that exist in the user's world rather
# than in the conversation: artefacts a side effect can actually change,
# and state a tool could actually have looked at.
#
# This is the single most important list in Phase 4, because it is what
# keeps the verifier from making ordinary conversation unusable. A side-
# effect verb on its own is not enough evidence that a sentence claims a
# side effect: "I checked the docs and Python is dynamically typed" and
# "I checked your calendar" share the verb and share nothing else. The
# first is a turn of phrase, the second is a claim about the user's world
# that Aura may not make without evidence. The object noun is what tells
# them apart, deterministically, without a language model.
#
# Membership is deliberately conservative. A noun goes in only when a
# false strict reading would be *worse* than a missed one - so "calendar",
# "email" and "file" are in, and "code", "options", "answer", "idea",
# "text" and "docs" are deliberately out, because Aura talks about those
# constantly and hedging them would be noise. A claim outside this
# vocabulary is still classified and still counted in diagnostics; it is
# simply not rewritten.
#
# The trailing `(?:e?s)?` carries the regular plural. Without it "You have
# three unread emails" fell outside the scope while "...unread email" fell
# inside it, because `\bmail\b` cannot match inside "emails" - a silent
# hole in the most common noun in the list. Irregular plurals are spelled
# out; a few nouns appear in both forms, which is harmless.
_WORLD_OBJECT = re.compile(
    r"\b("
    r"email|e-mail|mail|inbox|inboxes|message|messages|sms|text message|"
    r"whatsapp|telegram|zalo|"
    r"calendar|event|events|appointment|appointments|meeting|meetings|"
    r"schedule|reminder|reminders|alarm|alarms|"
    r"file|files|folder|folders|directory|directories|"
    r"document|documents|"
    r"photo|photos|picture|pictures|image|images|screenshot|"
    r"app|apps|application|applications|package|apk|"
    r"contact|contacts|note|notes|"
    r"setting|settings|notification|notifications|permission|permissions|"
    r"phone|device|screen|wifi|wi-fi|bluetooth|brightness|volume|"
    r"task|tasks|operation|"
    r"tin nhắn|thư|hộp thư|lịch|sự kiện|cuộc hẹn|cuộc họp|"
    r"nhắc|báo thức|tệp|tập tin|thư mục|tài liệu|ảnh|hình|"
    r"ứng dụng|danh bạ|ghi chú|cài đặt|thông báo|quyền|"
    r"điện thoại|thiết bị|màn hình|âm lượng|độ sáng"
    r")(?:e?s)?\b",
    re.IGNORECASE,
)

_FACTUAL_PATTERNS = re.compile(
    r"\b(contains?|has|have|is|are|was|were)\s+\d+|"
    r"\b(happens?|occurs?|scheduled|appointment|meeting|cuộc họp|"
    r"appointments|cuộc hẹn)\b|"
    r"\b(installed|uninstalled|present|present on|available on)\b|"
    r"\b(received|delivered)\b",
    re.IGNORECASE,
)
_EN_FIRST_PERSON = r"\b(i|i've|i have|i had|i'm|we've|tôi|em|mình)\b"

_ACTION_FIRST_PERSON = re.compile(
    rf"{_EN_FIRST_PERSON}(?:\s+[a-z']+)?(?:\s+[a-z']+)?(?:\s+[a-z']+)?\s+"
    rf"(?:successfully\s+)?(?:"
    rf"{_EN_ACTION_VERBS_ALT}|{_VI_ACTION_PHRASES_ALT}"
    rf")\b",
    re.IGNORECASE,
)


# ----------------------------------------------------------------------
# The claim record
# ----------------------------------------------------------------------

@dataclass
class Claim:
    """
    One extracted claim from a response, with its verification state.

    A claim is created by `extract_claims` with `state=None`; the
    verifier fills in `state`, `evidence_refs`, `hallucination` and,
    when the claim needed repair, `repair`.

    `type` is the primary class and `tags` holds the rest: a sentence
    can be both an IDENTITY and a NUMERICAL and a TEMPORAL claim.
    `GENERAL` claims are returned so callers can audit the whole reply,
    but the verifier never touches them.
    """

    id: str
    sentence: str
    type: str = ClaimType.GENERAL
    tags: frozenset = frozenset()
    state: ClaimState | None = None
    evidence_refs: list[str] = field(default_factory=list)
    hallucination: str = ""
    repair: str = ""
    notes: list[str] = field(default_factory=list)

    # Whether the sentence names something in the user's world (see
    # `_WORLD_OBJECT`). This is the repair layer's scope gate: a claim
    # that names no such object is recorded but never rewritten, which is
    # what keeps ordinary conversation natural.
    world: bool = False

    # Set when the evidence behind this claim disagrees with itself -
    # two recalled memories that cannot both be true. A separate fact
    # from UNKNOWN: "we have nothing" and "we have two answers" call for
    # different responses, and only the second is worth asking about.
    conflict: bool = False

    @property
    def in_scope(self) -> bool:
        """
        Whether this claim is one the verifier holds to evidence.

        Action claims always are - an assertion that a side effect
        happened is the strictest class there is, and the classifier
        already required a world object to reach it.

        Everything else, capability claims included, is in scope only when
        it names something in the user's world. "I can send SMS on your
        phone" is a claim about a device skill and gets checked against the
        registry; "I can help you with that" is a sentence in a
        conversation, and hedging it into "I'm not entirely sure I can do
        that" was a real output of the first pass - the precise failure
        mode the contract calls out. A CONTRADICTED capability claim is
        repaired regardless of scope; see `repair_claims`.
        """

        return self.type == ClaimType.ACTION or self.world

    def as_dict(self) -> dict:
        """Diagnostics form - no raw text, just the labels."""

        payload = {
            "id": self.id,
            "type": self.type,
            "tags": sorted(self.tags),
            "world": self.world,
        }

        if self.state is not None:
            payload["state"] = self.state.value

        if self.evidence_refs:
            payload["evidence_refs"] = self.evidence_refs

        if self.hallucination:
            payload["hallucination"] = self.hallucination

        if self.repair:
            payload["repaired"] = True

        return payload


def _classify(sentence: str) -> tuple[str, frozenset, bool]:
    """
    The primary class, tags and grounding scope of one sentence.

    Order matters: ACTION and CAPABILITY are checked first because their
    verb forms are also dictionary words ("verified"), and a claim that
    names a side effect is the strictest class.

    ACTION requires a side-effect verb AND a world object, or one of the
    external-outcome phrases ("the recipient received it", "completed
    successfully") which assert a world change on their own. The verb
    alone is not sufficient: it produces false strictness on ordinary
    sentences and that is the failure mode the contract calls out - a
    verifier that makes normal chat unusable has not made Aura more
    trustworthy, it has made it useless. See `_WORLD_OBJECT`.
    """

    tags: set[str] = set()

    world = bool(_WORLD_OBJECT.search(sentence))

    names_action = bool(
        _ACTION_FIRST_PERSON.search(sentence)
        or _ACTION_PASSIVE.search(sentence)
    )

    if (names_action and world) or _EXTERNAL_OUTCOME.search(sentence):
        return ClaimType.ACTION, frozenset(tags), world

    if any(pattern.search(sentence) for pattern in _CAPABILITY_PATTERNS):
        return ClaimType.CAPABILITY, frozenset(tags), world

    if _NUMERIC_PATTERN.search(sentence):
        tags.add(ClaimType.NUMERICAL)

    if _IDENTITY_PATTERN.search(sentence):
        tags.add(ClaimType.IDENTITY)

    if _TEMPORAL_PATTERN.search(sentence):
        tags.add(ClaimType.TEMPORAL)

    if _FACTUAL_PATTERNS.search(sentence):
        return ClaimType.FACTUAL, frozenset(tags), world

    if tags:
        # A bare "you have..." or "currently..." without a fact verb is
        # still a user-state claim the verifier should look at.
        return ClaimType.FACTUAL, frozenset(tags), world

    return ClaimType.GENERAL, frozenset(), world


def extract_claims(text: str) -> list[Claim]:
    """
    Deterministically extract the claims of a reply.

    Returns ALL sentences as Claim objects - GENERAL included, so a
    caller can audit the whole reply - but only non-GENERAL sentences
    are ever grounded or repaired downstream.

    `state`, `evidence_refs`, `hallucination` and `repair` are left
    empty; the verifier fills them in.
    """

    claims: list[Claim] = []

    for index, sentence in enumerate(_split_sentences(text)):

        claim_type, tags, world = _classify(sentence)

        claims.append(
            Claim(
                id=f"c{index + 1}",
                sentence=sentence,
                type=claim_type,
                tags=tags,
                world=world,
            )
        )

    return claims


def is_action_claim(claim: Claim) -> bool:
    """Whether this claim asserts a side effect happened."""

    return claim.type == ClaimType.ACTION


__all__ = [
    "Claim",
    "ClaimType",
    "extract_claims",
    "is_action_claim",
]